src/components/project/ManageProject.jsx
src/components/project/ProjectInfo.jsx
src/config.js
src/pages/WalletCreationPage.jsx

```js
const CurrentState = () => {
if (current === "Project Information") {
return (
<ProjectInfo
projectInfo={projectForm.projectInfo}
setProject={setProjectForm}
setCurrent={setCurrent} // current 변경 함수를 제공해줘 다른 곳에도
></ProjectInfo>
);
}
```
ManageProject 에서 컴포넌트를 컨트롤해주고있더라고. 여기서 current로 현재 상태를 관리하고 있길래 해당 부분을 set해주는 함수를 자식으로 넘겨줬어
```js
const ProjectInfo = ({ projectInfo, setProject, setCurrent }) => {
const changeCurrent = () => {
setCurrent("Basic Information"); // current 값을 다음 가야할 페이지 명으로 변경해
};
```
이건 ProjectInfo 자식 컴포넌트에서 받아오는 부분인데 이렇게 하면 사이드바 클릭하는 것이랑 같은 이벤트를 만들 수 있더라고
```js
<div className="mt-4">
<Button
size="md"
className="w-24"
onClick={() => {
validateAndSave();
changeCurrent(); // 클릭하면 이걸로 같이
}}
>
next
</Button>
</div>
```
마지막으로 버튼에 이벤트를 달면 끝! 이름도 save보다 next가 좋아보여서 바꿔봤어 …

feat: page 자동으로 넘어가기

---

src/Router.jsx
src/components/project/CreaterInfo.jsx
src/components/project/ProjectInfo.jsx
src/components/ui/AccordianCustomStyles.jsx
src/components/ui/DatePicker.jsx
src/config.js
src/pages/SignUpPage.jsx
src/pages/SignUpSucceedPage.jsx
src/pages/WalletCreationPage.jsx

implemented smoother sign up process

---

src/Router.jsx
src/components/ui/EcommerceCard.jsx
src/config.js
src/pages/CreateProjectPage.jsx
src/pages/ProjectsPage.jsx
src/pages/WalletCreationPage.jsx

connecting project service

---

src/components/ui/EcommerceCard.jsx
src/pages/ProjectsPage.jsx

connected project initiation

---

src/Router.jsx
src/components/project/BasicInfo.jsx
src/components/project/ManageProject.jsx
src/components/project/ProjectInfo.jsx
src/components/ui/DefaultSidebar.jsx
src/components/ui/EcommerceCard.jsx
src/config.js
src/pages/ProjectsPage.jsx

connected project service to server

---

src/assets/icons/xmark.svg
src/components/wallet/WalletMain.jsx
src/pages/LogInPage.jsx

can see private key at wallet modal from now on

---

package-lock.json
package.json
src/components/ui/StickyNavbar.jsx
src/components/wallet/WalletMain.jsx
src/contract/ERC20Contract.js

fixed error and added spinner

---

src/components/ui/navbar/NavList.jsx
src/pages/ProjectsPage.jsx

check token

---

src/pages/ProjectsPage.jsx

check token in useEffect

---

src/components/ui/navbar/AuthButton.jsx
src/components/ui/navbar/SearchBar.jsx

responsiveness test1

---

src/components/ui/CategoryBar.jsx
src/components/ui/EcommerceCard.jsx
src/components/ui/navbar/NavList.jsx
src/components/ui/navbar/NavbarHeader.jsx
src/components/ui/navbar/SearchBar.jsx
src/pages/MainPage.jsx
vite.config.js

responsiveness2

---

src/components/ui/navbar/SearchBar.jsx

responsiveness3

---

src/Router.jsx
src/components/ui/CategoryBar.jsx
src/components/ui/EcommerceCard.jsx
src/components/ui/MembershipBg.jsx
src/components/ui/navbar/AuthButton.jsx
src/components/ui/navbar/StickyNavbar.jsx
src/components/wallet/WalletModal.jsx
src/pages/LogInPage.jsx
src/pages/ProjectsPage.jsx
src/pages/SignUpPage.jsx
src/pages/SignUpSucceedPage.jsx
src/pages/WalletCreationPage.jsx

changed url

---

src/components/ui/navbar/NavList.jsx

changed Url2

---

src/pages/ProjectsPage.jsx

changedUrl3

---

src/components/project/ManageProject.jsx
src/components/ui/Card.jsx
src/components/ui/DefaultSidebar.jsx
src/components/ui/FooterWithLogo.jsx
src/components/ui/navbar/NavbarHeader.jsx

changedUrl4

---

src/Router.jsx
src/pages/ProjectDetailPage.jsx
src/pages/ProjectsPage.jsx

changedUrl5

---

.gitignore
src/config.js
src/pages/ProjectsListPage.jsx

connected project list page with api

---

package-lock.json
package.json
src/components/details/ProjectImage.jsx
src/components/details/ProjectTabs.jsx
src/components/ticket/NFTTicket.css
src/components/ticket/NFTTicket.jsx
src/components/ui/Card.jsx
src/components/ui/EcommerceCard.jsx
src/components/wallet/WalletHeader.jsx
src/components/wallet/WalletMain.jsx
src/pages/MyProjectsPage.jsx
src/pages/ProjectDetailPage.jsx
src/utils/formatPrice.js
tailwind.config.js

designed ticket

---

src/components/createProject/ManageProject.jsx
src/components/createProject/SuccessDialog.jsx
src/components/ticket/NFTTicket.jsx
src/components/ui/EcommerceCard.jsx

ticket generated after creating project

---

src/components/ui/EcommerceCard.jsx
src/components/ui/navbar/AuthButton.jsx
src/components/ui/navbar/NavList.jsx
src/components/ui/navbar/StickyNavbar.jsx
src/pages/LogInPage.jsx
src/pages/MyProjectsPage.jsx
src/pages/ProjectDetailPage.jsx
src/pages/ProjectsListPage.jsx
src/pages/SignUpPage.jsx
src/pages/SignUpSucceedPage.jsx
src/pages/WalletCreationPage.jsx

deleted fe route

---

src/components/createProject/ManageProject.jsx
src/components/createProject/SuccessDialog.css
src/components/createProject/SuccessDialog.jsx
src/components/ticket/NFTTicket.jsx
src/components/ui/Card.jsx
src/components/ui/DefaultSidebar.jsx
src/components/ui/MembershipBg.jsx
src/components/ui/navbar/NavbarHeader.jsx
src/pages/MainPage.jsx

base64 encoding in progress

---

src/components/createProject/ManageProject.jsx
src/components/ticket/NFTTicket.jsx

ticket now available

---

src/components/createProject/ManageProject.jsx
src/components/createProject/SuccessDialog.jsx
src/components/details/ProjectTabs.jsx
src/components/ticket/NFTTicket.jsx
src/config.js

NFT connected

---

src/components/ticket/NFTTicket.jsx

problem solved

---

src/components/ui/navbar/AuthButton.jsx

접속 시 토큰 만료됐지만 네비게이션 바에 로그인 된 것으로 보이는 문제 해결

loginStatusUpdated

---

src/components/ui/EcommerceCard.jsx
src/components/ui/navbar/NavList.jsx
src/components/wallet/PrivateKeyDialog.jsx
src/components/wallet/WalletHeader.jsx
src/components/wallet/WalletMain.jsx
src/pages/LogInPage.jsx
src/pages/MainPage.jsx
src/pages/MyProjectsPage.jsx
src/pages/ProjectsListPage.jsx

few updates has been made

---

src/components/ui/CheckoutModal.jsx
src/components/ui/CheckoutSuccessDialog.jsx
src/components/ui/ListWithAvatar.jsx
src/components/ui/animation/SuccessAnimation.css
src/components/ui/animation/SuccessAnimation.jsx
src/components/ui/navbar/AuthButton.jsx
src/components/ui/navbar/NavbarHeader.jsx
src/components/ui/navbar/StickyNavbar.jsx
src/components/wallet/WalletHeader.jsx
src/components/wallet/WalletMain.jsx
src/pages/MainPage.jsx
src/pages/ProjectDetailPage.jsx

demo checkout process
